# fly.toml app configuration file generated for b-trust-banking on 2025-10-21T01:07:27+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'b-trust-banking'
primary_region = 'sin'

[build]

[env]
  NODE_ENV = 'production'
  PORT = '3000'

[processes]
  app = 'npm start'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = '/health'
    protocol = 'http'
    tls_skip_verify = false

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/app/frontend/build'
  url_prefix = '/'
